<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FS7JD1M" ignored="0" name="Login Demo" tests="3" failures="1" timestamp="22 Feb 2020 12:11:18 GMT" time="32.923" errors="0">
  <testcase name="createNewUser" time="2.258" classname="SighUpTS.SighUPTC"/>
  <testcase name="loginSuccessfully" time="4.126" classname="LoginTS.LoginTC"/>
  <testcase name="verifyLoginSuccessfullyMsg" time="3.252" classname="LoginTS.LoginTC">
    <failure type="java.lang.AssertionError" message="Unable to display successfully Msg expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Unable to display successfully Msg expected [false] but found [true]
at LoginTS.LoginTC.verifyLoginSuccessfullyMsg(LoginTC.java:81)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginSuccessfullyMsg -->
</testsuite> <!-- Login Demo -->
